//Joaquín de Souza (270366)

package Interfaz;
import Dominio.*;
import java.util.*;
import javax.swing.JFrame;
import java.io.*;
import javax.swing.JOptionPane;

public class VentanaInicio extends javax.swing.JFrame {

    public VentanaInicio(Sistema sis) {
        modelo = sis;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClaroOscuro = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        gestionMenu = new javax.swing.JMenu();
        clientesMenuItem = new javax.swing.JMenuItem();
        vehiculosMenuItem = new javax.swing.JMenuItem();
        empleadosMenuItem = new javax.swing.JMenuItem();
        contratosMenuItem = new javax.swing.JMenuItem();
        movimientosMenu = new javax.swing.JMenu();
        entradasMenuItem = new javax.swing.JMenuItem();
        salidasMenuItem = new javax.swing.JMenuItem();
        serviciosAdicionalesMenuItem = new javax.swing.JMenuItem();
        variosMenu = new javax.swing.JMenu();
        reportesMenuItem = new javax.swing.JMenuItem();
        recuperacionDeDatosMenuItem = new javax.swing.JMenuItem();
        grabacionDeDatosMenuItem = new javax.swing.JMenuItem();
        miniJuegoMenuItem = new javax.swing.JMenuItem();
        informacionDeAutoresMenuItem = new javax.swing.JMenuItem();
        terminarMenu = new javax.swing.JMenu();
        salirMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnClaroOscuro.setText("Claro/Oscuro");
        btnClaroOscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaroOscuroActionPerformed(evt);
            }
        });
        getContentPane().add(btnClaroOscuro);
        btnClaroOscuro.setBounds(100, 190, 200, 40);

        gestionMenu.setMnemonic('f');
        gestionMenu.setText("Gestión");

        clientesMenuItem.setMnemonic('o');
        clientesMenuItem.setText("Clientes");
        clientesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesMenuItemActionPerformed(evt);
            }
        });
        gestionMenu.add(clientesMenuItem);

        vehiculosMenuItem.setMnemonic('s');
        vehiculosMenuItem.setText("Vehículos");
        vehiculosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiculosMenuItemActionPerformed(evt);
            }
        });
        gestionMenu.add(vehiculosMenuItem);

        empleadosMenuItem.setMnemonic('a');
        empleadosMenuItem.setText("Empleados");
        empleadosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadosMenuItemActionPerformed(evt);
            }
        });
        gestionMenu.add(empleadosMenuItem);

        contratosMenuItem.setMnemonic('x');
        contratosMenuItem.setText("Contratos");
        contratosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratosMenuItemActionPerformed(evt);
            }
        });
        gestionMenu.add(contratosMenuItem);

        menuBar.add(gestionMenu);

        movimientosMenu.setMnemonic('e');
        movimientosMenu.setText("Movimientos");

        entradasMenuItem.setMnemonic('t');
        entradasMenuItem.setText("Entradas");
        entradasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradasMenuItemActionPerformed(evt);
            }
        });
        movimientosMenu.add(entradasMenuItem);

        salidasMenuItem.setMnemonic('y');
        salidasMenuItem.setText("Salidas");
        salidasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidasMenuItemActionPerformed(evt);
            }
        });
        movimientosMenu.add(salidasMenuItem);

        serviciosAdicionalesMenuItem.setMnemonic('p');
        serviciosAdicionalesMenuItem.setText("Servicios Adicionales");
        serviciosAdicionalesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviciosAdicionalesMenuItemActionPerformed(evt);
            }
        });
        movimientosMenu.add(serviciosAdicionalesMenuItem);

        menuBar.add(movimientosMenu);

        variosMenu.setMnemonic('h');
        variosMenu.setText("Varios");

        reportesMenuItem.setMnemonic('c');
        reportesMenuItem.setText("Reportes");
        reportesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesMenuItemActionPerformed(evt);
            }
        });
        variosMenu.add(reportesMenuItem);

        recuperacionDeDatosMenuItem.setMnemonic('a');
        recuperacionDeDatosMenuItem.setText("Recuperación de datos");
        recuperacionDeDatosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recuperacionDeDatosMenuItemActionPerformed(evt);
            }
        });
        variosMenu.add(recuperacionDeDatosMenuItem);

        grabacionDeDatosMenuItem.setText("Grabación de datos");
        grabacionDeDatosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabacionDeDatosMenuItemActionPerformed(evt);
            }
        });
        variosMenu.add(grabacionDeDatosMenuItem);

        miniJuegoMenuItem.setText("MiniJuego");
        miniJuegoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniJuegoMenuItemActionPerformed(evt);
            }
        });
        variosMenu.add(miniJuegoMenuItem);

        informacionDeAutoresMenuItem.setText("Información de autores");
        informacionDeAutoresMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informacionDeAutoresMenuItemActionPerformed(evt);
            }
        });
        variosMenu.add(informacionDeAutoresMenuItem);

        menuBar.add(variosMenu);

        terminarMenu.setText("Terminar");

        salirMenuItem.setText("Salir");
        salirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuItemActionPerformed(evt);
            }
        });
        terminarMenu.add(salirMenuItem);

        menuBar.add(terminarMenu);

        setJMenuBar(menuBar);

        setBounds(0, 0, 400, 331);
    }// </editor-fold>//GEN-END:initComponents

    private void contratosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratosMenuItemActionPerformed
        VentanaContratos vent = new VentanaContratos(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_contratosMenuItemActionPerformed

    private void clientesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesMenuItemActionPerformed
        VentanaClientes vent = new VentanaClientes(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_clientesMenuItemActionPerformed

    private void empleadosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadosMenuItemActionPerformed
        VentanaEmpleados vent = new VentanaEmpleados(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_empleadosMenuItemActionPerformed

    private void entradasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradasMenuItemActionPerformed
        VentanaEntradas vent = new VentanaEntradas();
        vent.setVisible(true);
    }//GEN-LAST:event_entradasMenuItemActionPerformed

    private void serviciosAdicionalesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviciosAdicionalesMenuItemActionPerformed
        VentanaServicios vent = new VentanaServicios();
        vent.setVisible(true);
    }//GEN-LAST:event_serviciosAdicionalesMenuItemActionPerformed

    private void informacionDeAutoresMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacionDeAutoresMenuItemActionPerformed
        VentanaAutores vent = new VentanaAutores();
        vent.setVisible(true);
    }//GEN-LAST:event_informacionDeAutoresMenuItemActionPerformed

    private void salirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirMenuItemActionPerformed

    private void vehiculosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiculosMenuItemActionPerformed
        VentanaVehiculos vent = new VentanaVehiculos(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_vehiculosMenuItemActionPerformed

    private void salidasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidasMenuItemActionPerformed
        VentanaSalidas vent = new VentanaSalidas();
        vent.setVisible(true);
    }//GEN-LAST:event_salidasMenuItemActionPerformed

    private void reportesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesMenuItemActionPerformed
        VentanaReportes vent = new VentanaReportes(this, true, modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_reportesMenuItemActionPerformed

    private void miniJuegoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniJuegoMenuItemActionPerformed
        MiniJuego juego = new MiniJuego();
        juego.setVisible(true);
    }//GEN-LAST:event_miniJuegoMenuItemActionPerformed

    private void btnClaroOscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaroOscuroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClaroOscuroActionPerformed

    private void grabacionDeDatosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabacionDeDatosMenuItemActionPerformed
        try{
            FileOutputStream arch = new FileOutputStream("DATOS");
            ObjectOutputStream grabar = new ObjectOutputStream(arch);
            grabar.writeObject(modelo);
            grabar.close();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(this, e.getMessage() + "No se pudo serializar", "Error", 0);
        }
    }//GEN-LAST:event_grabacionDeDatosMenuItemActionPerformed

    private void recuperacionDeDatosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recuperacionDeDatosMenuItemActionPerformed
        try{    
            FileInputStream arch = new FileInputStream("DATOS");
            ObjectInputStream leer = new ObjectInputStream(arch);
            Sistema sis = (Sistema)leer.readObject();
            leer.close();
            modelo = sis;
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(this, e.getMessage() + "No se pudo des-serializar", "Error", 0);
        }
        catch (ClassNotFoundException e){
            JOptionPane.showMessageDialog(this, e.getMessage() + "Error al 'castear' el sistema", "Error", 0);
        }
    }//GEN-LAST:event_recuperacionDeDatosMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClaroOscuro;
    private javax.swing.JMenuItem clientesMenuItem;
    private javax.swing.JMenuItem contratosMenuItem;
    private javax.swing.JMenuItem empleadosMenuItem;
    private javax.swing.JMenuItem entradasMenuItem;
    private javax.swing.JMenu gestionMenu;
    private javax.swing.JMenuItem grabacionDeDatosMenuItem;
    private javax.swing.JMenuItem informacionDeAutoresMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miniJuegoMenuItem;
    private javax.swing.JMenu movimientosMenu;
    private javax.swing.JMenuItem recuperacionDeDatosMenuItem;
    private javax.swing.JMenuItem reportesMenuItem;
    private javax.swing.JMenuItem salidasMenuItem;
    private javax.swing.JMenuItem salirMenuItem;
    private javax.swing.JMenuItem serviciosAdicionalesMenuItem;
    private javax.swing.JMenu terminarMenu;
    private javax.swing.JMenu variosMenu;
    private javax.swing.JMenuItem vehiculosMenuItem;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;
}
